### ISSUE TITLE
JavaScript Promise & Rust Future Interoperability

### ISSUE THREAD

**Issue by Redfire75369** [Redfire75369/spiderfire#12]
## Issue
Although promises have been implemented, with the addition of the event loop, there is still an issue as native asynchronicity cannot be used. Every promise that is created requires its own native function to be made.

## Requirements
- Advanced Understanding of Rust and JavaScript Asynchronous Runtimes
- Understanding of codebase to utilise and enhance APIs

## Possible Solution
An API will need to be created that allows Rust Futures to be converted to JavaScript Promises. One possible plan of action is similar to [wasm-bindgen](https://rustwasm.github.io/wasm-bindgen/api/src/wasm_bindgen_futures/lib.rs.html#209-229), where the future is spawned in a seperate thread, and awaited. 

However, this would require a more flexible API for creating promises. Promises currently each require their own native function. Each promise converted from a future would need to be created dynamically. The most effective solution for this would be to allow callbacks for the creation of Promises, but I am unsure of how this could be done.

**Comment by Redfire75369** [comment]
This has now been completed with https://github.com/Redfire75369/spiderfire/commit/f4e448310f3189e2cae6ac63c55522c7420346f0.

The API is as follows:
```rs
let future = async {
    return Ok(Int32Value(4));
};

let promise = future_to_promise(rt.cx(), future);
unsafe { global.set_as(rt.cx(), "promiser".into(), IonObject::from(promise.raw())); }
assert!(IonScript::compile_and_evaluate(rt.cx(), "inline.js", "promiser.then(v => console.log(v))").is_ok());
```

As of https://github.com/Redfire75369/spiderfire/commit/7a2faf5c1667628a2555a8c27843a31a40573b42, `#[js_fn]` macros can also be used to create functions that return promises.

```rs
async fn async_increment(int: u64) -> u64 { int + 1 }

#[js_fn]
async unsafe fn async_fn(int: u64) -> Result<u64, ()>{
    Ok(async_increment(int).await)
}
```

This issue will be kept open for a week for any bugs in the API or possible improvements to the API.

**Comment by sagudev** [comment]
Why function unsafe?

**Comment by Redfire75369** [comment]
In `#[js_fn]`? It's the same for synchronous functions too. It's across FFI, so I think it's fair too.

**Comment by sagudev** [comment]
Yes but this function is called from other unsafe function that does the args conversion, which means that this function (`async_increment`) is safe, but it's calee is unsafe. So I would make unsafe fn on js_fn optional.

**Comment by Redfire75369** [comment]
After having talks with some people on the safety/unsafety of this function, it seems that it is still unsafe as long as panics have undefined behaviour. The solution to that seems to be `catch_unwind`.

I suppose that it could just return an `Err()` if a panic occurs.

**Comment by Redfire75369** [comment]
As of https://github.com/Redfire75369/spiderfire/commit/e333e88d2b316467c15c5d68e016d3befa11fc68, panicking within native functions is no longer undefined behaviour. The output is still a bit weird, but can be improved later.

As there are no further comments on the API for asynchronous functions, this issue will be closed.
