### ISSUE TITLE
Change default output colors to align with Node.js

### ISSUE THREAD

**Issue by joseywoermann** [Redfire75369/spiderfire#19]
Currently, different data types cause differently colored output, which (at least in my opinion) is distracting.

![grafik](https://user-images.githubusercontent.com/67111271/143492920-96e03191-29a2-496e-a599-21f59cb9b24f.png)

~~I would suggest changing the output to always be colored white.~~

**Comment by Redfire75369** [comment]
The colours for string and arrays should definitely be removed, I just haven't gotten around to it. I should probably add in the recursive printing for objects and arrays too, so it's consistent at least.

However, I'm not so sure for numbers, booleans and undefined/null. Node.js colours those as yellow, yellow and grey respectively.

**Comment by joseywoermann** [comment]
> The colours for string and arrays should definitely be removed, I just haven't gotten around to it. I should probably add in the recursive printing for objects and arrays too, so it's consistent at least.
> 
> However, I'm not so sure for numbers, booleans and undefined/null. Node.js colours those as yellow, yellow and grey respectively.

Doing it like Node.js sounds like a good idea, strings being green is my main issue.

**Comment by Redfire75369** [comment]
I probably won't use the same colours, but only numbers, booleans and undefined/null will be coloured.

**Comment by Redfire75369** [comment]
As of <https://github.com/Redfire75369/spiderfire/commit/f7dc8cdbceccc9b443518afbe90a66188a7889db>, the default output is white. Strings are only green when inside an array or an object. Objects also have a custom formatter so there will no longer be brackets around the objects.
