### ISSUE TITLE
Idea: Easier writing of native functions for SM

### ISSUE THREAD

**Issue by sagudev** [Redfire75369/spiderfire#4]
Now you are writing all functions naked for SpiderMonkey. Even Servo does not do that. It uses procedural macro (and WebIDL). Well WebIDL is probably overkill but [proc macros](https://doc.rust-lang.org/reference/procedural-macros.html)...

This is how it could look like:
```rust
#[jsfn]
pub fn print(s: String) {
      println!("rust said: {}", s)
}
```
and it would expend to:
```rust
unsafe extern "C" fn print(context: *mut JSContext, argc: u32, vp: *mut Value) -> bool {
    let args = Arguments::new(argc, vp);
    args.rval().set(UndefinedValue());

    if args.len != 1 {
        JS_ReportErrorASCII(context, b"print() requires exactly 1 argument\0".as_ptr() as *const libc::c_char);
        return false;
    }

    println!("{}", to_string(cx, args.value(0).unwrap()));

    return true;
}
```
It could also be applied for methods (like the one you uses in fs.rs). Something like this is also used in https://github.com/rjs-team/rjs look at `js_fn!` macro.

**Comment by Redfire75369** [comment]
First attempt at this can be found [here](https://github.com/Redfire75369/spiderfire/blob/feature/js_fn_macro/ion/src/functions/macros.rs). Functions with no parameters work fine. I have yet to test regular parameters yet, but it seems that varargs do not work yet either.

**Comment by Redfire75369** [comment]
After some more changes, I have gotten functions with no parameters, individual parameters and variable arguments to work. I will be switching the rest of the functions to use the macro.

The syntax is
```rs
#[macro_rules_attribute(js_fn!)]
fn log(val: String) -> IonResult<()> {
    println!("{}", val);

    Ok(())
}
```
