### ISSUE TITLE
Macro parsing succeeds on invalid input

### ISSUE THREAD

**Issue by Arshia001** [Redfire75369/spiderfire#40]
I used to have this code somewhere:

```rust
#[js_fn]
fn something(#[ion::this] this: Object) -> ...
```

and it was parsing OK, which it shouldn't have. Since the macros on the properties are being parsed out by `ion-proc`, I think it'd be better to fail with an error on such invalid syntax instead of ignoring it.

**Comment by Redfire75369** [comment]
I was looking to mostly revamp attribute parsing (again), so this shouldn't be that big a jump. I'll look into it.

**Comment by Arshia001** [comment]
Thanks!

**Comment by Redfire75369** [comment]
I was looking into this. The problem wasn't exactly being parsed out or what I expected. It turns out I was discarding all the attributes from a `PatType` when converting it to my internal `Parameter` struct.

**Comment by Redfire75369** [comment]
Fixed in d6b9ba0590df50bdd9fe7337ea84c7e105d46a4b
