### ISSUE TITLE
Converting an object with a bad toString implementation to a string crashes SpiderFire

### ISSUE THREAD

**Issue by Arshia001** [Redfire75369/spiderfire#46]
If this object:

```
{
        toString() { return {}; }
}
```

is fed into `String::from_value`, the entire process crashes with a segfault. This is because mozjs's `ToString` returns null when the conversion fails, but this is not checked so an `ion::String` with a null pointer is created.

**Comment by Redfire75369** [comment]
Fixed in afb931887d6086ff609a304fab54c1a58b863378
