### ISSUE TITLE
get_private and get_mut_private don't work with subclasses

### ISSUE THREAD

**Issue by Arshia001** [Redfire75369/spiderfire#50]
Having this:

```rust
#[js_class]
struct Base {
  reflector: Reflector
}

#[js_class]
struct Derived {
  base: Base
}

#[js_fn]
fn foo(bar: Base) { ... }
```

this JS code won't work:

```js
foo(new Derived())
```

Because the check in `get_private`/`get_mut_private` is eventually using `JS_InstanceOf` which only checks for the exact class provided. The fix is to have this in `ClassDefinition`:

```rust
	fn instance_or_subtype_of(cx: &Context, object: &Object) -> Result<bool> {
		let constructor: Function = cx.root(Self::class_info(cx).constructor).into();
		let constructor_obj = constructor.to_object(cx);
		let mut result = false;
		unsafe {
			if !JS_HasInstance(
				cx.as_ptr(),
				constructor_obj.handle().into(),
				Value::object(cx, object).handle().into(),
				&mut result as *mut bool,
			) {
				return Err(Error::none());
			}
		}
		Ok(result)
	}
```

and change the code in `get_(mut)_private` to:

```rust
	fn get_private<'a>(cx: &Context, object: &Object<'a>) -> Result<&'a Self> {
		if Self::instance_of(cx, object) // Fast path, most native objects don't have base classes and this check is way faster
		|| Self::instance_or_subtype_of(cx, object)?
		{
			Ok(unsafe { Self::get_private_unchecked(object) })
		} else {
			Err(private_error(Self::class()))
		}
	}
```

Simply casting the pointer of a derived native type (`Derived` in the example) to a less-derived native type (`Base` in the example) works because the base is always the first member and there's `#[repr(C)]` on `js_class`es which I assume was put in to support this scenario.

**Comment by Redfire75369** [comment]
To be exact, the `#[repr(C)]` is there to allow up/downcasting types, but that does allow allow this, yes.
