### ISSUE TITLE
[RFC] Macro for Native Classes

### ISSUE THREAD

**Issue by Redfire75369** [Redfire75369/spiderfire#9]
Extension of #4 for Classes

This is a low priority task, as procedural macros will most likely be required, and other aspects such as more standard modules and the event loop are more important to complete currently.

Proposed Syntax
```rs
#[js_class]
mod Name {
    struct Fields {
        str: String,
        num: u64
    }
    
    #[constructor]
    fn constructor() -> IonResult<Name> {
        Fields {
            str: "",
            num: 0
        }
    }
    
    fn method(#[this] this: IonObject, num: f64) -> IonResult<()> {
        println!("{}", this.str);
        this.set("num", num);
    }
    
    #[get]
    fn get(#[this] this: IonObject) -> IonResult<f64> {
        Ok(this.get("num"))
    }
    
    #[set]
    fn set(#[this] this: IonObject, String str) -> IonResult<()> {
        this.set("str", str);
        Ok(())
    }
}
```

**Comment by sagudev** [comment]
Here is how wasm-bindgen does this: https://rustwasm.github.io/wasm-bindgen/contributing/design/importing-js-struct.html

Although I think it would be better to have struct with specific trait for that. Something like:
```rust
#[js_class]
struct Fields {
    str: String,
    num: u64
}

impl CLASS for Fields {
    fn constructor() -> IonResult<Name> {
        Fields {
            str: "",
            num: 0
        }
    }
    fn get(self) -> IonResult<f64> {
        Ok(self.get("num"))
    }
    
    fn set(self , String str) -> IonResult<()> {
        self.set("str", str);
        Ok(())
    }
}

impl Fields {
    fn method(self, num: f64) -> IonResult<()> {
        println!("{}", self.str);
        this.set("num", num);
    }
}
```

**Comment by Redfire75369** [comment]
Hmm, this way of doing it would require impl's for `FromJSValConvertible` and `ToJSValConvertible` to be automatically created.

**Comment by Redfire75369** [comment]
I have a slightly improved idea for this:
```rs
#[js_class]
mod class {
    #[class]
    #[extends(OtherClass)]
    struct Class {
        #[convert(EnforceRange)]
        field: u8
    }
    
    impl Class {
        #[constructor]
        fn constructor() -> IonResult<Class> {
            Class { field: 644 }
        }
    
        #[js_fn]
        fn add(&self, #[convert(Clamp)] other: u8) -> IonResult<u8> {
            Ok(self.field + other)
        }
        
        #[js_get]
        fn f(&self) -> IonResult<u8> {
            Ok(self.field)
        }
        
        #[js_set]
        fn f(&mut self, field: u8) -> IonResult<()> {
            self.field = u8;
            Ok(())
        }
    }
}
```

Putting the attribute macro on the `mod` instead of one the struct is still required as access to the functions by the macro is required.

**Comment by sagudev** [comment]
Two functions named f?

**Comment by Redfire75369** [comment]
You can have both a getter and a setter with the same name, you just can't have a property and (getter and/or setter) with the same name.

**Comment by sagudev** [comment]
> You can have both a getter and a setter with the same name, you just can't have a property and (getter and/or setter) with the same name.

The only problem I have is that it does not look rusty enough. I would do with less attr macros, as the whole mod is already transformed using #[js_class].

**Comment by Redfire75369** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TypeScript Support](https://trello.com/c/FCCbbC4j/5-typescript-support)
